### PR TITLE
Draft: Improve jsx integration, add `autoDetect`, `autoDoctype`, `contentType` and `isHtml`.

### PR DESCRIPTION
**Pull request by arthurfiorette**
This current PR is a draft, which i talked about here https://github.com/elysiajs/elysia-html/issues/10#issuecomment-1712949960.

Changes:
- [x] Removed regex for auto detecting html, as there's no real way to do it right (see [1](https://stackoverflow.com/q/11229831) and [2](https://stackoverflow.com/q/1732348)) Provided better html detection based start, end and length.
- [x] Added autoDoctype to automatically attach `<!doctype html>` if not present.
- [x] Added autoDetect to optionally add content-type text/html to html strings.
- [x] Added contentType to provide ability to change the `text/html; charset=utf8` default value.
- [x] Added `isHtml` to allow the end user to customize the auto-html string detection if needed.
- [x] Tests all options and code paths.
- [x] Improve README & website documentation
  - [x] JSX
  - [x] All options covered with examples
  - [x] Should we also change https://elysiajs.com/plugins/html.html?

`elysia-html` should only be responsible for string -> html responses, but also having dedicated & documented support for JSX is needed. However, duplicating JSX declarations may not be the best answer here, [as it is currently done](https://github.com/elysiajs/elysia-html/blob/e04d152c863995f582ff59e2ac0558d059c79c74/src/declaration.ts). Some examples of it are the `style` property that [can be objects](https://github.com/kitajs/html/blob/5e9d05ebf673fa1afda955f001b1ef0e9d7c27eb/jsx.d.ts#L37) is [only string](https://github.com/elysiajs/elysia-html/blob/e04d152c863995f582ff59e2ac0558d059c79c74/src/declaration.ts#L33) in current implementation, [`hgroup` is not present](https://github.com/kitajs/html/pull/16) and many other future updates @kitajs/html will receive.

With v2.0.1+, the `@kitajs/html/register` import was added to automatically add `Html` namespace globally, which would kindly solve all current needs to re-export it and now is using a different name instead the `html()` function this plugin provides. 

But I'm also 100% ok to re-export @kitajs/html functions/typings under different names, just trying to find a convention with this package, so that no config changes need to be done when using or not using **elysiajs** framework!

Happy to help with anything else!

### CODE REVIEW

**Comment by arthurfiorette** [comment]
@SaltyAom whats your opnion in this PR?

**Comment by SaltyAom** [comment]
Thanks a lot, everything looks great! 

One thing I would like to add is the deletion of the declaration file.

Basically, I added that file to support custom attributes and custom HTML tags, because many developers tend to like HTMX which feature custom attribute / allowing developer to easily contribute with type declaration in the future.

**Comment by SaltyAom** [comment]
Alright, that sounds good to me.

I'll just add an extending Intrinsic Element on the doc instead of allowing custom component out of the box.

Thanks for your hard work.

Let me know if you want to edit the HTML plugin doc, otherwise I'll edit it myself once this PR is merged.

**Comment by arthurfiorette** [comment]
I think I got 100% coverage.

```ts
test/html.test.ts:
✓ Jsx html > auto return html [6.35ms]
✓ HTML > manual return html [0.75ms]
✓ HTML > inherits header [0.35ms]
✓ HTML > return any html tag [0.32ms]
✓ HTML > consistently identifies html content [0.38ms]

test/jsx.test.tsx:
✓ Jsx html > auto return html [0.60ms]
✓ HTML > manual return html [0.37ms]
✓ HTML > inherits header [0.29ms]
✓ HTML > return any html tag [0.50ms]
✓ HTML > consistently identifies html content [0.43ms]

test/options.test.ts:
✓ options > tests default contentType [0.32ms]
✓ options > tests custom contentType [0.45ms]
✓ options > tests default autoDetect [0.38ms]
✓ options > tests false autoDetect [0.83ms]
✓ options > tests default autoDoctype [0.31ms]
✓ options > tests false autoDoctype [0.29ms]
✓ options > tests true autoDoctype with non html tag [0.31ms]
✓ options > tests full autoDoctype [1.13ms]

test/is-html.test.tsx:
✓ isHtml > detects html [0.07ms]
✓ isHtml > detects html with JSX [0.14ms]
✓ isHtml > does not detects html on non strings [0.04ms]
✓ isHtml > does not detects html on non html strings [0.04ms]

test/index.test.ts:
✓ HTML > auto return html [0.42ms]
✓ HTML > manual return html [0.34ms]
✓ HTML > inherits header [0.33ms]
✓ HTML > return any html tag [0.26ms]
✓ HTML > consistently identifies html content [0.32ms]
```

**Comment by arthurfiorette** [comment]
Documentation changes: https://github.com/elysiajs/documentation/pull/106. I also swap this README to only contain a link to the official docs and avoid code duplicity.

**Comment by arthurfiorette** [comment]
@SaltyAom I think its ready for review now. Only breaking changes would be the JSX settings needed changes inside `tsconfig.json` and current users that uses buggy behaviors that now are fixed (very unlikely).

**Review by SaltyAom — APPROVED** [review]

**Comment by SaltyAom** [comment]
Finally got time to review this, this is really a good PR, thanks a lot for your hard work.

Shiroko thumb up

**Pull request merged**
