### PR TITLE
chore(package.json): update elysia to 0.6.10 (fixes #4)

### LINKED ISSUE #4: Property 'html' does not exist on type 'Context<{ body: unknown; params: Record<never, string>; query: undefined; headers: undefined; response: unknown; }, {}> & {}'
a simple app following the documentation instructions. but still get err

index.tsx
```typescript
import Elysia from "elysia";
import { html } from "@elysiajs/html";
import * as tHTML from "typed-html";
import staticPlugin from "@elysiajs/static";
import Home from "./components/Home";
import { About } from "./components/About";

new Elysia()
    .use(html())
    .use(staticPlugin())
    .get("/", ({ html }) =>
        html(
            <BaseHTML>
                <Home />
            </BaseHTML>
        )
    )
    .get("/about", ({ headers, html }) => {
        if (headers?.[`hx-request`]) {
            return <About />;
        }
        return html(
            <BaseHTML>
                <About />
            </BaseHTML>
        );
    })
    .listen(3000, ({ hostname, port }) =>
        console.log(`🦊 running on http://${hostname}:${port}`)
    );

const BaseHTML = ({ children }: tHTML.Children) => {
    return (
        <html lang="en">
            <head>
                <meta charset="UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <title>FireBEH</title>
                <link rel="stylesheet" href="public/style.css" />
                <script src="public/htmx.min.js"></script>
            </head>
            <body class="px-4 grid grid-rows-[min-content,1fr]">
                <nav class="flex justify-between">
                    <h1 class="py-4">FireBEH🔥</h1>
                    <div class="flex items-center">
                        <button
                            hx-get="/about"
                            hx-target="#pageContent"
                            hx-push-url="/about"
                        >
                            About
                        </button>
                    </div>
                </nav>
                <div class="flex justify-center items-center" id="pageContent">
                    {children}
                </div>
            </body>
        </html>
    );
};
```

error:
```typescript
[{
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'html' does not exist on type 'Context<{ body: unknown; params: Record<never, string>; query: undefined; headers: undefined; response: unknown; }, {}> & {}'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 18,
	"endLineNumber": 11,
	"endColumn": 22
}]
```

### PR DESCRIPTION
**Pull request by thekorn**
This fixes https://github.com/elysiajs/elysia-html/issues/4

While on it I also update the dev dependencies

- Update elysia version in peerDependencies to 0.6.10 for better compatibility
- Update versions of @types/node, bun-types, elysia, eslint, rimraf, typescript in devDependencies for bug fixes and new features

### CODE REVIEW

**Comment by t0mri** [comment]
no buddy. i tried updating Elysia to `0.6.10` it doesn't help

**Comment by thekorn** [comment]
@t0mri sorry, there might be a misunderstanding of how to get this issue fixed. Just in case, let me please rephrase: the fix is not about updating the elysia dependency of your application, but to use a version of elysia-html which is itself depending on an updated version. My proposal is to use lokal linking in order to check this fix:
1) clone my repo, and checkout this branch which includes the fix
2) bun build
3) bun link
4) change over to you app, and instead of using an upstream release of elysia-html use the local version you just build: bun link @elysiajs/html

See https://bun.sh/docs/cli/install#local-packages-bun-link for more information 

hope this helps

**Comment by hesxenon** [comment]
fyi, this currently prevents using elysia 0.6.11 since the resolved elysia types conflict

**Comment by thekorn** [comment]
thats fixed with most recent changes to elysia and elysia-html, kust make sure to use

import { Elysia } from 'elysia'
import { html } from '@elysiajs/html'

(instead of the previously documented import Elysia from 'elysia' ...

closing the PR

**Pull request closed without merging**
